# Site
name: "Saudável"
description: "Alimentação Personalizada"
meta_description: "ALGO CACTHY"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics:
disqus:
mailchimp-list:

# Authors
authors:
  bel:
    name: Bel
    display_name: Bel
    gravatar:
    email:
    web:
    twitter:
    description:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/:name/'
    tag: '/tag/:name/'


# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
